# Generated by Django 5.1.7 on 2025-08-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Reviewers',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('person_email', models.CharField(max_length=100)),
                ('slfm_department_compliance_id', models.IntegerField()),
                ('slfm_department_name', models.CharField(max_length=100)),
                ('sub_department_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Person Reviewer',
                'verbose_name_plural': 'Person Reviewers',
                'db_table': 'Person_Reviewers',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=50)),
                ('fund_status_id_fk', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'db_table': 'FUND',
                'indexes': [models.Index(fields=['fund_name'], name='FUND_fund_na_004b76_idx'), models.Index(fields=['fund_status_id_fk'], name='FUND_fund_st_00f328_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderType',
            fields=[
                ('service_provider_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Service Provider Type',
                'verbose_name_plural': 'Service Provider Types',
                'db_table': 'SERVICE_PROVIDER_TYPE',
                'indexes': [models.Index(fields=['type'], name='SERVICE_PRO_type_055c16_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subfund',
            fields=[
                ('subfund_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subfund_name', models.CharField(max_length=100)),
                ('is_subfund', models.BooleanField(help_text='0:No|1:Yes')),
                ('is_umbrella', models.BooleanField(help_text='0:No|1:Yes')),
                ('fund_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPL_Database.fund', verbose_name='Fund')),
            ],
            options={
                'verbose_name': 'Subfund',
                'verbose_name_plural': 'Subfunds',
                'db_table': 'SUBFUND',
                'indexes': [models.Index(fields=['fund_id_fk'], name='SUBFUND_fund_id_912568_idx'), models.Index(fields=['subfund_name'], name='SUBFUND_subfund_9eb918_idx')],
            },
        ),
    ]
