# Generated by Django 5.1.7 on 2025-08-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CPL_Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEP_Classifications',
            fields=[
                ('pep_classifications_id', models.AutoField(primary_key=True, serialize=False)),
                ('classification_status', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'PEP Classification',
                'verbose_name_plural': 'PEP Classifications',
                'db_table': 'PEP_Classifications',
            },
        ),
        migrations.CreateModel(
            name='PEP_Entities',
            fields=[
                ('pep_entities_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PEP Entity',
                'verbose_name_plural': 'PEP Entities',
                'db_table': 'PEP_Entities',
            },
        ),
        migrations.CreateModel(
            name='PEP_Estimations',
            fields=[
                ('pep_estimations_id', models.AutoField(primary_key=True, serialize=False)),
                ('estimation_status', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'PEP Estimation',
                'verbose_name_plural': 'PEP Estimations',
                'db_table': 'PEP_Estimations',
            },
        ),
        migrations.CreateModel(
            name='PEP_Name_Screening',
            fields=[
                ('pep_names_screening_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'PEP Name Screening',
                'verbose_name_plural': 'PEP Name Screenings',
                'db_table': 'PEP_Name_Screening',
            },
        ),
        migrations.CreateModel(
            name='PEP_Nationality',
            fields=[
                ('pep_nationality_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'PEP Nationality',
                'verbose_name_plural': 'PEP Nationalities',
                'db_table': 'PEP_Nationality',
            },
        ),
        migrations.CreateModel(
            name='PEP_Entities_Names',
            fields=[
                ('entities_names_id', models.AutoField(primary_key=True, serialize=False)),
                ('removed', models.BooleanField(default=False, help_text='0:No|1:Yes')),
                ('entities_id_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pep.pep_entities')),
            ],
            options={
                'verbose_name': 'PEP Entities-Names',
                'verbose_name_plural': 'PEP Entities_Names',
                'db_table': 'PEP_Entities_Names',
            },
        ),
        migrations.CreateModel(
            name='PEP_Dates',
            fields=[
                ('pep_dates_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_validation_rc', models.DateField(blank=True, null=True)),
                ('date_approval_mc', models.DateField(blank=True, null=True)),
                ('date_approval_brd', models.DateField(blank=True, null=True)),
                ('date_removal', models.DateField(blank=True, null=True)),
                ('date_updated_last', models.DateField(blank=True, null=True)),
                ('entities_names_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep.pep_entities_names')),
            ],
            options={
                'verbose_name': 'PEP Date',
                'verbose_name_plural': 'PEP Dates',
                'db_table': 'PEP_Dates',
            },
        ),
        migrations.CreateModel(
            name='PEP_Entities_Subfund',
            fields=[
                ('pep_entities_subfund_id', models.AutoField(primary_key=True, serialize=False)),
                ('entities_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pep.pep_entities')),
                ('subfund_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPL_Database.subfund')),
            ],
            options={
                'verbose_name': 'PEP Entities-Subfund',
                'verbose_name_plural': 'PEP Entities Subfund',
                'db_table': 'PEP_Entities_Subfund',
            },
        ),
        migrations.AddField(
            model_name='pep_entities',
            name='subfunds',
            field=models.ManyToManyField(through='pep.PEP_Entities_Subfund', to='CPL_Database.subfund'),
        ),
        migrations.CreateModel(
            name='PEP_Names',
            fields=[
                ('pep_names_id', models.AutoField(primary_key=True, serialize=False)),
                ('pep_name', models.CharField(default='No Name', max_length=255, null=True)),
                ('position', models.CharField(default='Unknown Position', max_length=100)),
            ],
            options={
                'verbose_name': 'PEP Name',
                'verbose_name_plural': 'PEP Names',
                'db_table': 'PEP_Names',
                'indexes': [models.Index(fields=['pep_name'], name='PEP_Names_pep_nam_2fdd01_idx'), models.Index(fields=['position'], name='PEP_Names_positio_4094b1_idx')],
            },
        ),
        migrations.AddField(
            model_name='pep_entities_names',
            name='names_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep.pep_names'),
        ),
        migrations.CreateModel(
            name='PEP_Info',
            fields=[
                ('pep_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_screening', models.TextField(null=True)),
                ('comment_assessment', models.TextField(null=True)),
                ('is_rr_validated', models.BooleanField(help_text='0:No|1:Yes', null=True)),
                ('comment_mc_board', models.TextField(null=True)),
                ('pep_remove_reason', models.TextField(blank=True, null=True)),
                ('entities_names_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep.pep_entities_names')),
                ('pep_dates_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='pep.pep_dates')),
                ('person_reviewers_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_reviewers', to='CPL_Database.person_reviewers')),
                ('rc_validation_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rc_validations', to='CPL_Database.person_reviewers')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_type', to='CPL_Database.serviceprovidertype')),
                ('slamlux_classification_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slamlux_classification', to='pep.pep_classifications')),
                ('slamlux_estimation_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slamlux_estimation', to='pep.pep_estimations')),
                ('ta_classification_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_classification', to='pep.pep_classifications')),
                ('ta_estimation_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_estimation', to='pep.pep_estimations')),
                ('pep_names_screening_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep.pep_name_screening')),
                ('pep_nationality_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='pep.pep_nationality')),
            ],
            options={
                'verbose_name': 'PEP Info',
                'verbose_name_plural': 'PEP Infos',
                'db_table': 'PEP_Info',
            },
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['entities_names_id_fk'], name='PEP_Dates_entitie_0799ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['date_added'], name='PEP_Dates_date_ad_0cb0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['date_validation_rc'], name='PEP_Dates_date_va_19b9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['date_approval_mc'], name='PEP_Dates_date_ap_454236_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['date_approval_brd'], name='PEP_Dates_date_ap_7becdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['date_removal'], name='PEP_Dates_date_re_e478c9_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_dates',
            index=models.Index(fields=['date_updated_last'], name='PEP_Dates_date_up_f3aff7_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_entities_subfund',
            index=models.Index(fields=['entities_id_fk'], name='PEP_Entitie_entitie_44a4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_entities_subfund',
            index=models.Index(fields=['subfund_id_fk'], name='PEP_Entitie_subfund_496c01_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_entities',
            index=models.Index(fields=['entity_name'], name='PEP_Entitie_entity__d95bab_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_entities_names',
            index=models.Index(fields=['entities_id_fk'], name='PEP_Entitie_entitie_d889bf_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_entities_names',
            index=models.Index(fields=['names_id_fk'], name='PEP_Entitie_names_i_101e17_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['entities_names_id_fk'], name='PEP_Info_entitie_4633e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['pep_names_screening_id_fk'], name='PEP_Info_pep_nam_b63a05_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['person_reviewers_id_fk'], name='PEP_Info_person__260229_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['rc_validation_id_fk'], name='PEP_Info_rc_vali_a45ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['slamlux_classification_id_fk'], name='PEP_Info_slamlux_79c74f_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['ta_classification_id_fk'], name='PEP_Info_ta_clas_4e23d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['slamlux_estimation_id_fk'], name='PEP_Info_slamlux_78166f_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['ta_estimation_id_fk'], name='PEP_Info_ta_esti_6c02d4_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['pep_nationality_id_fk'], name='PEP_Info_pep_nat_177a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['pep_dates_id_fk'], name='PEP_Info_pep_dat_f942eb_idx'),
        ),
        migrations.AddIndex(
            model_name='pep_info',
            index=models.Index(fields=['service_provider'], name='PEP_Info_service_8c5cf9_idx'),
        ),
    ]
