# Generated by Django 5.1.7 on 2025-08-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CPL_Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COI_Cases',
            fields=[
                ('coi_cases_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_of_conflict', models.CharField(max_length=150)),
                ('event_description', models.TextField(null=True)),
                ('removed', models.BooleanField(default=False, help_text='0:No|1:Yes')),
            ],
            options={
                'verbose_name': 'COI Case',
                'verbose_name_plural': 'COI Cases',
                'db_table': 'COI_Cases',
            },
        ),
        migrations.CreateModel(
            name='COI_Status',
            fields=[
                ('coi_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'COI Status',
                'verbose_name_plural': 'COI Status',
                'db_table': 'COI_Status',
            },
        ),
        migrations.CreateModel(
            name='COI_Cases_Subfund',
            fields=[
                ('coi_cases_subfund_id', models.AutoField(primary_key=True, serialize=False)),
                ('cases_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conflict_of_interests.coi_cases')),
                ('subfund_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPL_Database.subfund')),
            ],
            options={
                'verbose_name': 'COI Cases-Subfund',
                'verbose_name_plural': 'COI Cases Subfund',
                'db_table': 'COI_Cases_Subfund',
            },
        ),
        migrations.AddField(
            model_name='coi_cases',
            name='subfunds',
            field=models.ManyToManyField(through='conflict_of_interests.COI_Cases_Subfund', to='CPL_Database.subfund'),
        ),
        migrations.CreateModel(
            name='COI_Dates',
            fields=[
                ('coi_dates_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_review_mc', models.DateField(blank=True, null=True)),
                ('date_review_brd', models.DateField(blank=True, null=True)),
                ('date_removal', models.DateField(blank=True, null=True)),
                ('date_updated_last', models.DateField(blank=True, null=True)),
                ('cases_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conflict_of_interests.coi_cases', verbose_name='Case')),
            ],
            options={
                'verbose_name': 'COI Date',
                'verbose_name_plural': 'COI Dates',
                'db_table': 'COI_Dates',
            },
        ),
        migrations.CreateModel(
            name='COI_Info',
            fields=[
                ('coi_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('isProven', models.BooleanField(help_text='0:Theoretical|1:Proven')),
                ('unit', models.TextField(null=True)),
                ('mitigation_measures', models.TextField(null=True)),
                ('isInvestorInformed', models.BooleanField(help_text='0:Theoretical|1:Proven', verbose_name='Is Investor Informed')),
                ('cases_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='conflict_of_interests.coi_cases', verbose_name='Cases')),
                ('coi_dates_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='conflict_of_interests.coi_dates')),
                ('status_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='conflict_of_interests.coi_status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'COI Info',
                'verbose_name_plural': 'COI Infos',
                'db_table': 'COI_Info',
            },
        ),
        migrations.AddIndex(
            model_name='coi_cases_subfund',
            index=models.Index(fields=['cases_id_fk'], name='COI_Cases_S_cases_i_ab523b_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_cases_subfund',
            index=models.Index(fields=['subfund_id_fk'], name='COI_Cases_S_subfund_795fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_cases',
            index=models.Index(fields=['area_of_conflict'], name='COI_Cases_area_of_1ee72b_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_dates',
            index=models.Index(fields=['cases_id_fk'], name='COI_Dates_cases_i_e40124_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_dates',
            index=models.Index(fields=['date_added'], name='COI_Dates_date_ad_d6a0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_dates',
            index=models.Index(fields=['date_review_mc'], name='COI_Dates_date_re_0293d4_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_dates',
            index=models.Index(fields=['date_review_brd'], name='COI_Dates_date_re_8f5eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_dates',
            index=models.Index(fields=['date_removal'], name='COI_Dates_date_re_1d6b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_dates',
            index=models.Index(fields=['date_updated_last'], name='COI_Dates_date_up_cdf335_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_info',
            index=models.Index(fields=['cases_id_fk'], name='COI_Info_cases_i_cb4b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_info',
            index=models.Index(fields=['status_id_fk'], name='COI_Info_status__cd56c9_idx'),
        ),
        migrations.AddIndex(
            model_name='coi_info',
            index=models.Index(fields=['coi_dates_id_fk'], name='COI_Info_coi_dat_89874f_idx'),
        ),
    ]
